version: '3'
services:
    centrifugo:
        image: centrifugo/centrifugo
        environment:
            - CENTRIFUGO_SECRET=my-secret-token
            - CENTRIFUGO_API_KEY=my-api-key
            - CENTRIFUGO_ADMIN_PASSWORD=admin
            - CENTRIFUGO_ADMIN_SECRET=admin
        command: centrifugo --config=config.json
        ports:
            - "8001:8000"
        volumes:
            - ./conf/centrifugo.json:/config.json
