services:
    web:
        build:
            context: containers/nginx
        container_name: rta-web
        ports:
            - "1000:80"
            - "1001:443"
        expose:
            - "1001"
        volumes:
            - ../:/var/www/html/code
            - ./containers/nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - rta-network
    php:
        build:
            context: containers/php
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        image: rta-php
        container_name: rta-php
        ports:
            - "${PHP_PORT:-9000}:9000"
        volumes:
            - ../:/var/www/html/code
            - ./containers/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - rta-network
    mercure:
        image: dunglas/mercure
        container_name: rta-mercure
        environment:
            SERVER_NAME: 'http://127.0.0.1'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://127.0.0.1:80 http://0.0.0.0:1000
                anonymous
                demo
        ports:
            - 80:80
        networks:
            - rta-network
    centrifugo:
        image: centrifugo/centrifugo:v5
        container_name: rta-centrifugo
        environment:
            - CENTRIFUGO_API_KEY=my-api-key
            - CENTRIFUGO_ADMIN_PASSWORD=admin
            - CENTRIFUGO_ADMIN_SECRET=admin
        ports:
            - "8000:8000"
        volumes:
            - ./config.json:/centrifugo/config.json
        command: centrifugo -c config.json
        networks:
            - rta-network
    redis:
        image: redis:latest
        container_name: rta-redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        restart: always
        networks:
            - rta-network
    rabbitmq:
        build:
            context: ./containers/rabbitmq
            dockerfile: Dockerfile
        container_name: rta-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=user
        ports:
            - "5672:5672"
            - "15674:15674"
        networks:
            - rta-network

volumes:
    redis_data:

networks:
    rta-network:
        external: true
        driver: bridge
