version: '3'
services:
    centrifugo:
        image: dunglas/mercure
        environment:
            - JWT_KEY=myJWTKey
            - DEMO=1
            - ALLOW_ANONYMOUS=1
            - CORS_ALLOWED_ORIGINS=*
            - PUBLISH_ALLOWED_ORIGINS='http://localhost'
        ports:
            - "80:80"
