version: '3'
services:
    rabbitmq:
        build: 
          context: .
          dockerfile: Dockerfile
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=user
        ports:
            - "5672:5672"
            - "15674:15674"
